### ISSUE TITLE
Beta aware during login

### ISSUE THREAD

**Issue by stevepeak** [asyncy/cli#52]
Is someone logs in they should be allowed to "signup" but they are should be unable to create apps.

1. The CLI should be aware that they are awaiting a Beta invitation and warn them if waiting.
2. The CLI should allow them to validate stories.
3. Upon signing up we should add the user to the CRM and email them with Beta access details.

**Comment by stevepeak** [comment]
Yes, I'm down for that.

**Comment by stevepeak** [comment]
@judepereira need review of the following pulls:
- [ ] https://github.com/asyncy/login.asyncyapp.com/pull/4
- [ ] https://github.com/asyncy/database/pull/54
- [ ] https://github.com/asyncy/cli/pull/59
- [ ] *Waiting* https://github.com/asyncy/login.asyncy.com/issues/1

**Comment by judepereira** [comment]
Fixed.
