### ISSUE TITLE
Address command aliases in shell completion

### ISSUE THREAD

**Issue by anukul** [asyncy/cli#76]
I'm using [click-contrib/click-completion](https://github.com/click-contrib/click-completion) to close #69, but it completes command names (`apps-create`, `apps-destroy`), while we primarily use aliases (`apps:create`, `apps:destroy`)

I see a couple of options for how to proceed:

1. We get rid of the colon alias and go with the command name (hyphens or something else).

2. We can try to add alias support to the completion library, but I'm not entirely sure of whether that will be accepted because it's dependent on the internal API of the 3rd party package [hotoffthehamster/click-alias](https://github.com/hotoffthehamster/click-alias) and also, a command might have multiple aliases in which case returning all matches doesn't seem to be the best idea.

    However, we can still patch it on our end and just have it return the first alias.
    There's a small problem with this, when click-completion sends the results to zsh, it [uses](https://github.com/click-contrib/click-completion/blob/master/click_completion/core.py#L232) the colon character to demarcate the command name and the command help text. I haven't yet been able to figure out the right escape sequence but it should be fixable afaik, if we go with this option.

3. We restructure the commands into groups (`apps` group with subcommands `create`, `destroy`, etc.)

**Comment by judepereira** [comment]
@stevepeak The issue here is that zsh can't handle `:` as a completion for some reason. Anukul has mentioned that it works for bash, but fails for zsh.

Thoughts on what to do about this? The cleanest approach would be to drop the `:`, and be identical to Kubectl and docker:
```
$ asyncy apps create
$ asyncy apps deploy
$ asyncy config set ...
$ asyncy config
$ asyncy releases
$ asyncy releases rollback
```

**Comment by stevepeak** [comment]
I agree doing `apps create` looks the cleanest. Any reasons/conflicts this would have? None come to my mind at first.

**Comment by judepereira** [comment]
Same, I like it too. @anukul Can you create a new branch, and change this behaviour? We need to support `apps:create` as well, but print a message that says `apps create` is the way forward. Don't mix this in with your shell completion PR.

**Comment by anukul** [comment]
This is almost ready, pending response on https://github.com/click-contrib/click-completion/pull/22
