### ISSUE TITLE
More verbosity

### ISSUE THREAD

**Issue by judepereira** [asyncy/cli#9]
I, as a user, don't know what happened after I hit `asyncy restart`. It just said okay. It feels like a black hole here. Can we get it to automatically run `docker-compose logs -f`?

**Comment by stevepeak** [comment]
👍 Fixed

**Comment by judepereira** [comment]
@stevepeak Are we doing the `docker-compose logs -f`?

**Comment by judepereira** [comment]
Quick update, I see `asyncy logs -f` seems to work. Can we mention this in the output of the start command, after the stack is up?
